---
deployment:
  tasks:
    - export DEPLOYPATH=/home/omarmham/public_html/
    - /bin/cp -R public_html/index.html $DEPLOYPATH
    - /bin/cp -R public_html/contact.html $DEPLOYPATH
    - /bin/cp -R public_html/contact-success.html $DEPLOYPATH
    - /bin/cp -R public_html/output.css $DEPLOYPATH
    - /bin/cp -R public_html/sitemap.xml $DEPLOYPATH
    - /bin/cp -R public_html/robots.txt $DEPLOYPATH
    - /bin/cp -R public_html/assets $DEPLOYPATH
    - /bin/cp -R public_html/projects $DEPLOYPATH
    - /bin/cp -R public_html/js $DEPLOYPATH 
