---
deployment:
  tasks:
    - export DEPLOYPATH=/home/omarmham/public_html/
    - /bin/cp -R public/index.html $DEPLOYPATH
    - /bin/cp -R public/contact.html $DEPLOYPATH
    - /bin/cp -R public/contact-success.html $DEPLOYPATH
    - /bin/cp -R public/output.css $DEPLOYPATH
    - /bin/cp -R public/sitemap.xml $DEPLOYPATH
    - /bin/cp -R public/robots.txt $DEPLOYPATH
    - /bin/cp -R public/assets $DEPLOYPATH
    - /bin/cp -R public/projects $DEPLOYPATH
    - /bin/cp -R public/js $DEPLOYPATH 
